rg_name: wus-lab-1-config-5-rg
network_sec_groups:
  nsg1db:
    name: "nsg-1-db"
    rule:
      name: "nsg-db"
      access: "allow"
      protocol: "Tcp"
      priority: 1000
      src_addr_pref: "10.0.0.0/16"
      src_port_ranges: "*"
      dst_addr_pref: "*"
      dst_port_ranges: 3306
  nsg2backend:
    name: "nsg-2-backend"
    rule:
      name: "nsg-backend"
      access: "allow"
      protocol: "Tcp"
      priority: 1000
      src_addr_pref: "*"
      src_port_ranges: "*"
      dst_addr_pref: "*"
      dst_port_ranges: "8100-8102"
  nsg3frontend:
    name: "nsg-3-frontend"
    rule:
      name: "nsg-frontend"
      access: "allow"
      protocol: "Tcp"
      priority: 1000
      src_addr_pref: "*"
      src_port_ranges: "*"
      dst_addr_pref: "*"
      dst_port_ranges: "22-8001"

subnets:
  subnet1db:
    name: "subnet-1-db"
    addr_pref: "10.0.1.0/24"
    nsg: "nsg-1-db"
  subnet2backend:
    name: "subnet-2-backend"
    addr_pref: "10.0.2.0/24"
    nsg: "nsg-2-backend"
  subnet3frontend:
    name: "subnet-3-frontend"
    addr_pref: "10.0.3.0/24"
    nsg: "nsg-3-frontend"

public_ips:
  - backend_ip
  - frontend_ip

vms:
  db_master:
    subnet: "subnet-1-db"
    nsg: "nsg-1-db"
    public_ip: ""
    name: "vm-1-db-master"
    IP: "10.0.1.20"
  backend:
    subnet: "subnet-2-backend"
    nsg: "nsg-2-backend"
    public_ip: "backend_ip"
    name: "vm-2-backend" 
    IP: "10.0.2.20"
  frontend:
    subnet: "subnet-3-frontend"
    nsg: "nsg-3-frontend"
    public_ip: "frontend_ip"
    name: "vm-3-frontend"
    IP: "10.0.3.20"
  db_slave:
    subnet: "subnet-1-db"
    nsg: "nsg-1-db"
    public_ip: ""
    name: "vm-4-db-slave"
    IP: "10.0.4.20"

components:
  db_master:
    type: "db_master"
    vm_name: "vm-1-db-master"
    port: 3306
  backend_1:
    type: "backend"
    vm_name: "vm-2-backend" 
    port: 8100
    related:
      - db_master
  backend_2:
    type: "backend"
    vm_name: "vm-2-backend" 
    port: 8101
    related:
      - db_master
  load_balancer:
    type: "load_balancer"
    vm_name: "vm-3-frontend"
    vm_config: "frontend"
    port: 8001
    related:
      - {component: backend_1, vm: backend}
      - {component: backend_2, vm: backend}
  frontend:
    type: "frontend"
    vm_name: "vm-3-frontend"
    port: 8000
    related: 
      - {component: load_balancer, vm: frontend}
  db_slave:
    type: "db_slave"
    vm_name: "vm-4-db-slave"
    port: 3307
    related: 
      - {component: db_master, vm: db_master}
